version: "3.9"
services:
  apollo-client:
    image: nextapolloclient
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - next-apollo-app
  apollo-server:
    image: nextapolloserver
    ports:
      - "4000:4000"
    networks:
      - next-apollo-app
networks:
  next-apollo-app:
    driver: bridge
